[project]
name = "mephi_23-61_project2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yuliya-mv", email = "yuu.khoang@gmail.com" }
]
requires-python = ">=3.12,<4.0"

dependencies = [
    "prettytable>=3.18.0",
    "prompt>=0.4.1,<0.5.0",
]

[tool.poetry]
packages = [
    { include = "primitive_db", from = "src" }
]

[tool.poetry.scripts]
database = "src.primitive_db.main:main"

[project.scripts]
database = "primitive_db.main:main"

[dependency-groups]
dev = [
    "ruff",
]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.uv]
package = true

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[build-system]
requires = ["uv_build>=0.8.0,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "primitive_db"
module-root = "src"
